name: CI Package

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/workflows/setup-uv-env
        with:
          python-version: "3.10"
          install-dev-dependencies: true
      - name: Test and Coverage
        run: |
          uv run coverage run -m pytest
          uv run coverage report --fail-under=95
      - name: Check Code Format (black)
        run: |
          uv run black -l 120 --check .
